In [1]:
"""
Una cadena de Markov (CM) es un tipo particular de proceso estocástico. Una CM 
tiene probabilidades de transición estacionarias, es decir, no dependen del tiempo. 
Las probabilidades del estado siguiente dependen únicamente del estado presente y 
no de los estados pasados.
Esto permite que la CM se pueda representar de manera compacata con un grafo. Por ejemplo:


En este caso la CM tiene dos estados. Los parámetros de las aristas son las 
probabilidades de transición de estado.

Por ejemplo, en esta CM la probabilidad de transitar del estado 1 al estado 2 es de 0.7.

Esto lo denotamos como  P(st+1=2∣st=1)=0.7
"""

'\nUna cadena de Markov (CM) es un tipo particular de proceso estocástico. Una CM \ntiene probabilidades de transición estacionarias, es decir, no dependen del tiempo. \nLas probabilidades del estado siguiente dependen únicamente del estado presente y \nno de los estados pasados.\nEsto permite que la CM se pueda representar de manera compacata con un grafo. Por ejemplo:\n\n\nEn este caso la CM tiene dos estados. Los parámetros de las aristas son las \nprobabilidades de transición de estado.\n\nPor ejemplo, en esta CM la probabilidad de transitar del estado 1 al estado 2 es de 0.7.\n\nEsto lo denotamos como  P(st+1=2∣st=1)=0.7\n'

In [2]:
"""
Las probabilidades de transición de una cadena de Markov se pueden representar 
de manera matricial.
En este caso la matrix de probabilidades de transición  T
queda dada por:

T=[0.30.70.60.4]

En python podemos utilizar el paquete científico numpy. La manera de 
representar esta matriz en Python es como sigue:
"""

'\nLas probabilidades de transición de una cadena de Markov se pueden representar \nde manera matricial.\nEn este caso la matrix de probabilidades de transición  T\nqueda dada por:\n\nT=[0.30.70.60.4]\n\nEn python podemos utilizar el paquete científico numpy. La manera de \nrepresentar esta matriz en Python es como sigue:\n'

In [14]:
!pip install numpy

  Cache entry deserialization failed, entry ignored
You are using pip version 9.0.3, however version 24.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [15]:

import numpy as np

T = np.matrix([[0.3,0.6],[0.7,0.4]])
print(T)

[[0.3 0.6]
 [0.7 0.4]]


In [16]:
x = np.matrix([[1],[0]])
print('x =\n'+str(x))
x_1 = np.matmul(T,x)
print('x(t+1)=\n'+str(x_1))
x_2 = np.matmul(T,x_1)
print('x(t+2)=\n'+str(x_2))

x =
[[1]
 [0]]
x(t+1)=
[[0.3]
 [0.7]]
x(t+2)=
[[0.51]
 [0.49]]


In [17]:
x_2 = np.matmul(np.linalg.matrix_power(T,2),x)
print('x(t+2)=\n'+str(x_2))

x(t+2)=
[[0.51]
 [0.49]]


In [18]:
def calcula_dist(T,x_0,n):
    x_n = np.matmul(np.linalg.matrix_power(T,n),x_0)
    print('x(t+'+str(n)+')=\n'+str(x_n))

In [19]:
x_5 = calcula_dist(T,x,5)

x(t+5)=
[[0.46023]
 [0.53977]]


In [20]:
for i in range(10):
    calcula_dist(T,x,i)

x(t+0)=
[[1.]
 [0.]]
x(t+1)=
[[0.3]
 [0.7]]
x(t+2)=
[[0.51]
 [0.49]]
x(t+3)=
[[0.447]
 [0.553]]
x(t+4)=
[[0.4659]
 [0.5341]]
x(t+5)=
[[0.46023]
 [0.53977]]
x(t+6)=
[[0.461931]
 [0.538069]]
x(t+7)=
[[0.4614207]
 [0.5385793]]
x(t+8)=
[[0.46157379]
 [0.53842621]]
x(t+9)=
[[0.46152786]
 [0.53847214]]


In [21]:
l,v = np.linalg.eig(T)
print(l)
print(v)

[-0.3  1. ]
[[-0.70710678 -0.65079137]
 [ 0.70710678 -0.7592566 ]]


In [22]:
x_s = v[:,1] / sum(v[:,1])
print(x_s)

[[0.46153846]
 [0.53846154]]


In [ ]:
# comienza por definir la matriz de probabilidad T
# T = 

# define un estado inicial, por ejemplo que el agente se encuentra en b
# x = 

# ¿que pasa al iterar 50 veces la ecuación?
#calcula_dist(T,x,50)

# Calcula eigenvectores
#l,v = np.linalg.eig(T)
#print(l)
#print(v)

# Identifica la columna correspondiente para el eigenvalor 1
# recuerda que en Python los índices comienzan en 0
#columna  =

#normaliza para obtener la distribución
#x_s = v[:,columna] / sum(v[:,columna])
#print(x_s)

#compara tus resultados ¿es la mísma distribución?

In [24]:
T=np.matrix([[0.7,0.4,0.2],[0.1,0.4,0.2],[0.2,0.2,0.6]]) #matriz([[eleme,elem],[elmen,elemst],[elemes,elems]])
#print(T)

x=np.matrix([[0],[1],[0]]) #Agente inicial, donde empieza, en este caso b
#print(x)

#x_50=calcula_dist(T,x,50) #que pasa al iterar 50 veces, para eso sirve el metodo

##Calculo de los eigenvectores
l,v = np.linalg.eig(T)  #Sirve para calcular los eigenvectores
#print(l) #Arroja los valores propios de la matriz(raices)
#print(v) #Arroja los vectores propios de la matriz

columna=0  #Escoger el valor que tenga 1 de los valroes propios (Vector l)
x_s = v[:,columna] / sum(v[:,columna]) #Sirve para normalizar el vector
print(x_s)

[[0.47619048]
 [0.19047619]
 [0.33333333]]
